---
- name: restart ntp
  service:
    name: "{{ ntp_daemon }}"
    state: restarted
  when:
    - not (ansible_check_mode | bool)
    - ntp_enabled | bool

- name: restart cron
  service:
    name: "{{ ntp_cron_daemon }}"
    state: restarted
  when:
    - not (ansible_check_mode | bool)
    - ntp_cron_handler_enabled | bool
